version: "3.9"
services:
  web-service:
    image: ubuntu:latest
    container_name: my-pet-web-service
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "18080:8080"
      - "122:22"
    volumes:
      - ~/dev/docker/volume/my-pet-web-service:/root/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 500M

  db:
    image: mysql:8.0
    container_name: my-pet-db
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mypet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
