version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: my-pet-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/ubuntu/project/redis/data:/data
      - /home/ubuntu/project/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  proxy:
    image: nginx:latest
    container_name: my-pet-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/ubuntu/project/proxy/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/project/proxy/keys:/etc/letsencrypt/live/my-pet.o-r.kr/
      - /home/ubuntu/project/proxy/log/nginx:/var/log/nginx
    environment:
      - TZ=Asia/Seoul
