INSERT INTO pet_category(type, name, parent_id, created_at, modified_at)
VALUES ('DOG', '초소형', NULL, NOW(), NOW())
     , ('DOG', '소형', NULL, NOW(), NOW())
     , ('DOG', '중형', NULL, NOW(), NOW())
     , ('DOG', '대형', NULL, NOW(), NOW())
     , ('DOG', '초대형', NULL, NOW(), NOW())
;

SELECT id
INTO @v_parent_id
FROM pet_category
WHERE name = '초소형';
INSERT INTO pet_category(type, name, parent_id, created_at, modified_at)
VALUES ('DOG', '러시안 토이', @v_parent_id, NOW(), NOW())
     , ('DOG', '말티즈', @v_parent_id, NOW(), NOW())
     , ('DOG', '볼로네즈', @v_parent_id, NOW(), NOW())
     , ('DOG', '쁘띠 브라반숑', @v_parent_id, NOW(), NOW())
     , ('DOG', '오스트레일리언 실키 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '요크셔테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '잉글리시 토이 테리어 블랙 앤드 탠', @v_parent_id, NOW(), NOW())
     , ('DOG', '재패니스 친', @v_parent_id, NOW(), NOW())
     , ('DOG', '차이니스 크레스티드', @v_parent_id, NOW(), NOW())
     , ('DOG', '치와와', @v_parent_id, NOW(), NOW())
     , ('DOG', '콘티넨탈 토이 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '포메라니안', @v_parent_id, NOW(), NOW())
;

SELECT id
INTO @v_parent_id
FROM pet_category
WHERE name = '소형';
INSERT INTO pet_category(type, name, parent_id, created_at, modified_at)
VALUES ('DOG', '그리폰 브뤼셀', @v_parent_id, NOW(), NOW())
     , ('DOG', '노르웨이 룬트훈트', @v_parent_id, NOW(), NOW())
     , ('DOG', '노리치 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '노퍽 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '닥스훈트', @v_parent_id, NOW(), NOW())
     , ('DOG', '대니시 스웨디시 팜독', @v_parent_id, NOW(), NOW())
     , ('DOG', '댄디 딘몬트 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '더치 스모우스혼트', @v_parent_id, NOW(), NOW())
     , ('DOG', '라사압소', @v_parent_id, NOW(), NOW())
     , ('DOG', '레이클랜드 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '로첸(리틀 라이온 독)', @v_parent_id, NOW(), NOW())
     , ('DOG', '맨체스터 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '무디', @v_parent_id, NOW(), NOW())
     , ('DOG', '미니어처 슈나우저', @v_parent_id, NOW(), NOW())
     , ('DOG', '미니어처 핀셔', @v_parent_id, NOW(), NOW())
     , ('DOG', '바셋 포브 드 브르타뉴', @v_parent_id, NOW(), NOW())
     , ('DOG', '베들링턴 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '벨지안 그리폰', @v_parent_id, NOW(), NOW())
     , ('DOG', '보더 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '보스턴 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '불 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '브라질리언 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '비숑 프리제', @v_parent_id, NOW(), NOW())
     , ('DOG', '셰틀랜드 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '스웨디시 발훈트(비지고딕 스피츠)', @v_parent_id, NOW(), NOW())
     , ('DOG', '스카이 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '스코티시 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '스키퍼키', @v_parent_id, NOW(), NOW())
     , ('DOG', '시바', @v_parent_id, NOW(), NOW())
     , ('DOG', '시츄', @v_parent_id, NOW(), NOW())
     , ('DOG', '실리엄 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '아펜핀셔', @v_parent_id, NOW(), NOW())
     , ('DOG', '오베르뉴 포인터', @v_parent_id, NOW(), NOW())
     , ('DOG', '오스트레일리안 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '웨스트 하일랜드 화이트 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '웰시 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '이탈리안 그레이하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '이탈리안 볼피노', @v_parent_id, NOW(), NOW())
     , ('DOG', '재패니즈 스피츠', @v_parent_id, NOW(), NOW())
     , ('DOG', '재패니즈 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '잭 러셀 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '저먼 헌팅 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '체스키 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '카발리에 킹 찰스 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '케언 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '코통 드 튈레아르', @v_parent_id, NOW(), NOW())
     , ('DOG', '킹 찰스 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '티벳탄 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '파슨 러셀 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '퍼그', @v_parent_id, NOW(), NOW())
     , ('DOG', '페키니즈', @v_parent_id, NOW(), NOW())
     , ('DOG', '포르투기즈 와런 하운드(포르투기즈 포덴고)', @v_parent_id, NOW(), NOW())
     , ('DOG', '폭스 테리어 스무스', @v_parent_id, NOW(), NOW())
     , ('DOG', '폭스 테리어 와이어', @v_parent_id, NOW(), NOW())
     , ('DOG', '푸미', @v_parent_id, NOW(), NOW())
     , ('DOG', '피레니안 셰퍼드, 스무스 페이스드', @v_parent_id, NOW(), NOW())
     , ('DOG', '피레니안 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '허배너스', @v_parent_id, NOW(), NOW())
     , ('DOG', '휘핏', @v_parent_id, NOW(), NOW())
;

SELECT id
INTO @v_parent_id
FROM pet_category
WHERE name = '중형';
INSERT INTO pet_category(type, name, parent_id, created_at, modified_at)
VALUES ('DOG', '가스콘 세인톤죠이스', @v_parent_id, NOW(), NOW())
     , ('DOG', '그랜드 바셋 그리폰 방뎅', @v_parent_id, NOW(), NOW())
     , ('DOG', '그리폰 니베르네', @v_parent_id, NOW(), NOW())
     , ('DOG', '그릭 헤어하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '기슈', @v_parent_id, NOW(), NOW())
     , ('DOG', '노르보텐스피츠', @v_parent_id, NOW(), NOW())
     , ('DOG', '노르웨이안 부훈트', @v_parent_id, NOW(), NOW())
     , ('DOG', '노르웨이안 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '노르웨이언 엘크하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '노바 스코셔 덕 톨링 레트리버', @v_parent_id, NOW(), NOW())
     , ('DOG', '더치 샤펜도스', @v_parent_id, NOW(), NOW())
     , ('DOG', '도베르만', @v_parent_id, NOW(), NOW())
     , ('DOG', '드레버', @v_parent_id, NOW(), NOW())
     , ('DOG', '라포니안 허더', @v_parent_id, NOW(), NOW())
     , ('DOG', '러시안-유러피안 라이카', @v_parent_id, NOW(), NOW())
     , ('DOG', '로마그나 워터 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '멕시칸 헤어리스 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '몬터니그런 마운틴 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '미디움 사이즈드 앵글로 프렌치 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '바바리안 마운틴 센트 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '바베트', @v_parent_id, NOW(), NOW())
     , ('DOG', '바센지', @v_parent_id, NOW(), NOW())
     , ('DOG', '바셋 블뢰 드 가스코뉴', @v_parent_id, NOW(), NOW())
     , ('DOG', '바셋 아르테지앙 노르만', @v_parent_id, NOW(), NOW())
     , ('DOG', '베르가마스코 셰퍼드 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '벨지안 셰퍼드 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '보더 콜리', @v_parent_id, NOW(), NOW())
     , ('DOG', '보스니안 브로큰 헤어드 하운드(바락)', @v_parent_id, NOW(), NOW())
     , ('DOG', '부르보네 포인팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '부비에 드 아르덴느', @v_parent_id, NOW(), NOW())
     , ('DOG', '불독', @v_parent_id, NOW(), NOW())
     , ('DOG', '브리케 그리폰 방댕', @v_parent_id, NOW(), NOW())
     , ('DOG', '브리트니 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '블루 가스코니 그리폰', @v_parent_id, NOW(), NOW())
     , ('DOG', '블루 피카르디 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '비글', @v_parent_id, NOW(), NOW())
     , ('DOG', '비글 해리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '비어디드 콜리', @v_parent_id, NOW(), NOW())
     , ('DOG', '쁘띠 바셋 그리폰 방댕', @v_parent_id, NOW(), NOW())
     , ('DOG', '사모예드', @v_parent_id, NOW(), NOW())
     , ('DOG', '살루키', @v_parent_id, NOW(), NOW())
     , ('DOG', '샤페이', @v_parent_id, NOW(), NOW())
     , ('DOG', '서식스 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '세르비안 트라이컬러 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '세르비안 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '세인트 저먼 포인터', @v_parent_id, NOW(), NOW())
     , ('DOG', '슈나우저', @v_parent_id, NOW(), NOW())
     , ('DOG', '스말랜드스퇴바레', @v_parent_id, NOW(), NOW())
     , ('DOG', '스몰 블루 가스코니', @v_parent_id, NOW(), NOW())
     , ('DOG', '스웨디시 라프훈트', @v_parent_id, NOW(), NOW())
     , ('DOG', '스위스 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '스타포드셔 불 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '스테비훈', @v_parent_id, NOW(), NOW())
     , ('DOG', '스패니시 워터 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '스패니시 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '스피츠', @v_parent_id, NOW(), NOW())
     , ('DOG', '슬로바키안 와이어 헤어드 포인터', @v_parent_id, NOW(), NOW())
     , ('DOG', '슬로바키안 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '슬루기', @v_parent_id, NOW(), NOW())
     , ('DOG', '시르네코 델레트나', @v_parent_id, NOW(), NOW())
     , ('DOG', '시베리안 허스키', @v_parent_id, NOW(), NOW())
     , ('DOG', '시코쿠', @v_parent_id, NOW(), NOW())
     , ('DOG', '실레르스퇴바레', @v_parent_id, NOW(), NOW())
     , ('DOG', '아리에쥬아', @v_parent_id, NOW(), NOW())
     , ('DOG', '아메리칸 스태퍼드셔 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '아메리칸 워터 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '아메리칸 코커 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '아메리칸 폭스하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '아이리시 글렌 오브 이말 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '아이리시 레드 세터', @v_parent_id, NOW(), NOW())
     , ('DOG', '아이리시 레드 앤드 화이트 세터', @v_parent_id, NOW(), NOW())
     , ('DOG', '아이리시 소프트코티드 휘튼 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '아이리시 워터 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '아이리시 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '아이슬랜드 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '아펜젤러 세넨훈드', @v_parent_id, NOW(), NOW())
     , ('DOG', '알라스칸 말라뮤트', @v_parent_id, NOW(), NOW())
     , ('DOG', '알파인 닥스브라크', @v_parent_id, NOW(), NOW())
     , ('DOG', '에리에지 포인팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '에어데일 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '엔틀버쳐 캐틀 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '오스트레일리안 셰퍼드', @v_parent_id, NOW(), NOW())
     , ('DOG', '오스트레일리안 스텀피 테일 캐틀 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '오스트레일리안 켈피', @v_parent_id, NOW(), NOW())
     , ('DOG', '오스트리안 블랙 앤드 탄 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '오스트리안 핀셔', @v_parent_id, NOW(), NOW())
     , ('DOG', '와이어-헤어드 포인팅 그리폰 코르탈스', @v_parent_id, NOW(), NOW())
     , ('DOG', '웨스트 시베리안 라이카', @v_parent_id, NOW(), NOW())
     , ('DOG', '웨스트팔리안 닥스브라케', @v_parent_id, NOW(), NOW())
     , ('DOG', '웰시 스프링어 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '웰시 코기', @v_parent_id, NOW(), NOW())
     , ('DOG', '유라시안', @v_parent_id, NOW(), NOW())
     , ('DOG', '이비전 포덴코', @v_parent_id, NOW(), NOW())
     , ('DOG', '이스트 시베리안 라이카', @v_parent_id, NOW(), NOW())
     , ('DOG', '이스트리안 쇼트-헤어드 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '이스트리안 와이어-헤어드 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '이탈리안 쇼트 헤어드 세구죠', @v_parent_id, NOW(), NOW())
     , ('DOG', '이탈리안 콜스 헤어드 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '잉글리시 세터 (르웰린)', @v_parent_id, NOW(), NOW())
     , ('DOG', '잉글리시 스프링거 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '잉글리시 코커 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '저먼 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '저먼 핀셔', @v_parent_id, NOW(), NOW())
     , ('DOG', '저먼 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '진돗개', @v_parent_id, NOW(), NOW())
     , ('DOG', '차우차우', @v_parent_id, NOW(), NOW())
     , ('DOG', '카르스트 셰퍼드 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '카이', @v_parent_id, NOW(), NOW())
     , ('DOG', '카탈란 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '커릴리언 베어 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '케리 블루 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '케이넌 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '콜리 러프', @v_parent_id, NOW(), NOW())
     , ('DOG', '콜리 스무스', @v_parent_id, NOW(), NOW())
     , ('DOG', '콜스-헤어드 스타이리안 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '쿠이커혼제', @v_parent_id, NOW(), NOW())
     , ('DOG', '크로아티안 셰퍼드 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '크롬폴란데', @v_parent_id, NOW(), NOW())
     , ('DOG', '클라인 문스터렌더', @v_parent_id, NOW(), NOW())
     , ('DOG', '타이 리지백', @v_parent_id, NOW(), NOW())
     , ('DOG', '타이완 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '티롤리언 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '티베탄 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '페루비안 잉카 오키드', @v_parent_id, NOW(), NOW())
     , ('DOG', '펨브록 웰시 코기', @v_parent_id, NOW(), NOW())
     , ('DOG', '포르셀엔', @v_parent_id, NOW(), NOW())
     , ('DOG', '포르투기즈 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '포르투기즈 워터 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '포르투기즈 포인팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '포사바츠 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '폰 브리태니 그리폰', @v_parent_id, NOW(), NOW())
     , ('DOG', '폴리시 로랜드 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '폴리시 헌팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '퐁토드메르 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '푸들', @v_parent_id, NOW(), NOW())
     , ('DOG', '풀리', @v_parent_id, NOW(), NOW())
     , ('DOG', '프렌치 불독', @v_parent_id, NOW(), NOW())
     , ('DOG', '프렌치 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '프렌치 포인팅 독(피레니안)', @v_parent_id, NOW(), NOW())
     , ('DOG', '피니쉬 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '피니시 스피츠', @v_parent_id, NOW(), NOW())
     , ('DOG', '피카디 셰퍼드', @v_parent_id, NOW(), NOW())
     , ('DOG', '핀란드 라포니안 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '필드 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '하노베리언 센트 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '하이겐 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '할덴 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '해리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '헝가리안 쇼트-헤어드 포인터(비즐라)', @v_parent_id, NOW(), NOW())
     , ('DOG', '홋카이도', @v_parent_id, NOW(), NOW())
;

SELECT id
INTO @v_parent_id
FROM pet_category
WHERE name = '대형';
INSERT INTO pet_category(type, name, parent_id, created_at, modified_at)
VALUES ('DOG', '고든 세터', @v_parent_id, NOW(), NOW())
     , ('DOG', '골든 리트리버', @v_parent_id, NOW(), NOW())
     , ('DOG', '그랜드 그리폰 방뎅', @v_parent_id, NOW(), NOW())
     , ('DOG', '그레이 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '그레이트 가스코니 블루', @v_parent_id, NOW(), NOW())
     , ('DOG', '그레이트 스위스 마운틴 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '그레이트 앵글로-프렌치 트라이컬러 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '그레이트 앵글로-프렌치 화이트 앤드 블랙 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '그레이트 앵글로-프렌치 화이트 앤드 오렌지 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '그린란드견', @v_parent_id, NOW(), NOW())
     , ('DOG', '달마시안', @v_parent_id, NOW(), NOW())
     , ('DOG', '더치 셰퍼드 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '도고 아르헨티노', @v_parent_id, NOW(), NOW())
     , ('DOG', '도이치 스티첼할', @v_parent_id, NOW(), NOW())
     , ('DOG', '드렌츠허 파트레이스', @v_parent_id, NOW(), NOW())
     , ('DOG', '디어하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '라브라도 리트리버', @v_parent_id, NOW(), NOW())
     , ('DOG', '라지 문스터랜더', @v_parent_id, NOW(), NOW())
     , ('DOG', '러시안 블랙 테리어', @v_parent_id, NOW(), NOW())
     , ('DOG', '로디지안 리지백', @v_parent_id, NOW(), NOW())
     , ('DOG', '로마니안 미오리틱 셰퍼드 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '로마니안 카르파티안 셰퍼드 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '마요르카 마스티프', @v_parent_id, NOW(), NOW())
     , ('DOG', '마요르카 셰퍼드 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '머레머 앤드 아브루츠 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '바셋하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '벌고 포인팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '보르조이', @v_parent_id, NOW(), NOW())
     , ('DOG', '보스 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '보헤미안 와이어 헤어드 포인팅 그리폰', @v_parent_id, NOW(), NOW())
     , ('DOG', '복서', @v_parent_id, NOW(), NOW())
     , ('DOG', '부비에 데 플랑드르', @v_parent_id, NOW(), NOW())
     , ('DOG', '브리아드', @v_parent_id, NOW(), NOW())
     , ('DOG', '블랙 앤 탄 쿤하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '블러드 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '빌리', @v_parent_id, NOW(), NOW())
     , ('DOG', '뿌아뚜방', @v_parent_id, NOW(), NOW())
     , ('DOG', '사를로스 울프혼드', @v_parent_id, NOW(), NOW())
     , ('DOG', '세인트 미구엘 캐틀 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '스패니시 그레이하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '슬로바키안 쿠바크', @v_parent_id, NOW(), NOW())
     , ('DOG', '시마론 우루과이', @v_parent_id, NOW(), NOW())
     , ('DOG', '아르토이스 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '아메리칸 아키타', @v_parent_id, NOW(), NOW())
     , ('DOG', '아키타', @v_parent_id, NOW(), NOW())
     , ('DOG', '아프간 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '알렌테조 라페이로', @v_parent_id, NOW(), NOW())
     , ('DOG', '에이디', @v_parent_id, NOW(), NOW())
     , ('DOG', '오터 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '올드 대니시 포인팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '올드 잉글리시 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '와이마라너', @v_parent_id, NOW(), NOW())
     , ('DOG', '이탈리안 스피노네', @v_parent_id, NOW(), NOW())
     , ('DOG', '이탈리안 포인팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '잉글리시 포인터', @v_parent_id, NOW(), NOW())
     , ('DOG', '잉글리시 폭스하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '자이언트 슈나우저', @v_parent_id, NOW(), NOW())
     , ('DOG', '잠트훈트', @v_parent_id, NOW(), NOW())
     , ('DOG', '저먼 롱헤어드 포인팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '저먼 셰퍼드', @v_parent_id, NOW(), NOW())
     , ('DOG', '저먼 쇼트-헤어드 포인팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '저먼 와이어헤어드 포인팅 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '체서피크 베이 리트리버', @v_parent_id, NOW(), NOW())
     , ('DOG', '체코슬로바키아 늑대개', @v_parent_id, NOW(), NOW())
     , ('DOG', '카나리안 와런 하운드(포덴고 카나리오)', @v_parent_id, NOW(), NOW())
     , ('DOG', '카네코르소', @v_parent_id, NOW(), NOW())
     , ('DOG', '카스트로 라보레이로 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '컬리 코티드 리트리버', @v_parent_id, NOW(), NOW())
     , ('DOG', '코몬돌', @v_parent_id, NOW(), NOW())
     , ('DOG', '쿠바츠', @v_parent_id, NOW(), NOW())
     , ('DOG', '클럼버 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '타트라 마운틴 쉽독', @v_parent_id, NOW(), NOW())
     , ('DOG', '파라오 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '폴리시 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '푸델포인터', @v_parent_id, NOW(), NOW())
     , ('DOG', '프레사 카나리오', @v_parent_id, NOW(), NOW())
     , ('DOG', '프렌치 트라이컬러 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '프렌치 포인팅 독(가스코뉴)', @v_parent_id, NOW(), NOW())
     , ('DOG', '프렌치 화이트 앤드 블랙 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '프렌치 화이트 앤드 오렌지 하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '프리지안 워터 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '플랫 코티드 리트리버', @v_parent_id, NOW(), NOW())
     , ('DOG', '피카디 스패니얼', @v_parent_id, NOW(), NOW())
     , ('DOG', '해밀턴스퇴바레', @v_parent_id, NOW(), NOW())
     , ('DOG', '헝가리안 그레이하운드(마자르 아가)', @v_parent_id, NOW(), NOW())
     , ('DOG', '헝가리안 와이어-헤어드 포인터(비즐라) 소개', @v_parent_id, NOW(), NOW())
     , ('DOG', '호바와트', @v_parent_id, NOW(), NOW())
     , ('DOG', '화이트 스위스 셰퍼드 독', @v_parent_id, NOW(), NOW())
;


SELECT id
INTO @v_parent_id
FROM pet_category
WHERE name = '초대형';
INSERT INTO pet_category(type, name, parent_id, created_at, modified_at)
VALUES ('DOG', '그레이트 데인', @v_parent_id, NOW(), NOW())
     , ('DOG', '나폴리탄 마스티프', @v_parent_id, NOW(), NOW())
     , ('DOG', '뉴펀들랜드', @v_parent_id, NOW(), NOW())
     , ('DOG', '도그 드 보르도', @v_parent_id, NOW(), NOW())
     , ('DOG', '랜시어', @v_parent_id, NOW(), NOW())
     , ('DOG', '레온베르거', @v_parent_id, NOW(), NOW())
     , ('DOG', '로트바일러', @v_parent_id, NOW(), NOW())
     , ('DOG', '마스티프', @v_parent_id, NOW(), NOW())
     , ('DOG', '버니즈 마운틴 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '불마스티프', @v_parent_id, NOW(), NOW())
     , ('DOG', '브로홀머', @v_parent_id, NOW(), NOW())
     , ('DOG', '세인트 버나드', @v_parent_id, NOW(), NOW())
     , ('DOG', '스패니시 마스티프', @v_parent_id, NOW(), NOW())
     , ('DOG', '아이리시 울프하운드', @v_parent_id, NOW(), NOW())
     , ('DOG', '에스트렐라 캐틀 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '캉갈 셰퍼드 독', @v_parent_id, NOW(), NOW())
     , ('DOG', '티베탄 마스티프', @v_parent_id, NOW(), NOW())
     , ('DOG', '피레니안 마스티프', @v_parent_id, NOW(), NOW())
     , ('DOG', '피레니안 마운틴 독', @v_parent_id, NOW(), NOW())
;
