spring:
  profiles:
    active:
      - local
    group:
      local:
        - db
        - infra
        - security
        - aws
      test:
        - db
        - infra
        - security
        - aws
      dev:
        - db
        - infra
        - security
        - aws
