name: Deploy My pet to Amazon EC2

on:
  push:
    branches:
      - develop
    pull_request:
      - develop

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: |
          mkdir -p deploy/
          cp appspec.yml deploy/
          cp -r scripts deploy/scripts/
          mkdir -p deploy/build
          cp my-pet-api/build/libs/*.jar deploy/build/
          cd deploy && zip -r $GITHUB_SHA.zip *
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./deploy/$GITHUB_SHA.zip s3://${{ secrets.AWS_DEPLOY_BUCKET }}/$GITHUB_SHA.zip

      - name: Code Deploy
        run: | 
          aws deploy create-deployment \
          --application-name ${{ secrets.AWS_DEPLOY_APP }} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name ${{ secrets.AWS_DEPLOY_GROUP }} \
          --s3-location bucket=${{ secrets.AWS_DEPLOY_BUCKET }},bundleType=zip,key=$GITHUB_SHA.zip
